# Generated by Django 6.0.4 on 2026-04-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carify_app', '0008_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='contact_info',
            field=models.CharField(blank=True, help_text='Direct contact details (e.g. Phone/Email)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='service_videos/'),
        ),
    ]
