# Generated by Django 6.0.4 on 2026-05-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carify_app', '0013_servicemedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text='Stripe Express connected account ID (acct_xxx)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='stripe_onboarding_complete',
            field=models.BooleanField(default=False, help_text='True once vendor completes Stripe onboarding'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='stripe_payouts_enabled',
            field=models.BooleanField(default=False, help_text='Mirrors Stripe payouts_enabled flag'),
        ),
    ]
