"""
Django settings for carify_project project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-4tkb-k4$v0*!&ih6o+a%w4+4&a8cu5%6me8$z-fil468++$#9s')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False').lower() == 'true'

# Keep development hosts working out of the box while allowing overrides in env.
default_allowed_hosts = ['127.0.0.1', 'localhost', 'testserver', '.onrender.com', '.carify.org']
env_allowed_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [
    host.strip() for host in env_allowed_hosts.split(',') if host.strip()
] or default_allowed_hosts


# Application definition

INSTALLED_APPS = [
    'unfold',
    'colorfield',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.apple',
    'rest_framework',
    'django_filters',
    'carify_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'carify_app.backends.CaseSensitiveAuthBackend',
]

SITE_ID = 1

ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    },
    'facebook': {
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile'],
        'FIELDS': ['email', 'name', 'first_name', 'last_name'],
    },
    'apple': {
        'APP': {
            'client_id': 'your.apple.client.id',
            'team_id': 'your_apple_team_id',
            'key_id': 'your_apple_key_id',
            'secret': 'your_apple_private_key',
        }
    }
}

ROOT_URLCONF = 'carify_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'carify_app' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'carify_project.wsgi.application'


# Database configuration with production overrides
DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600
    )
}

# Preserve explicit MySQL config if environment variables are present
if all(os.environ.get(k) for k in ['DB_NAME', 'DB_USER']):
    DATABASES['default'].update({
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    })


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# Password validation disabled for rapid development/testing
AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ('en', _('English')),
    ('es', _('Spanish')),
    ('fr', _('French')),
    ('ar', _('Arabic')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Whitenoise compression and caching
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Stripe settings
STRIPE_PUBLIC_KEY = os.environ.get('STRIPE_PUBLIC_KEY', '')
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')

# UNFOLD settings
UNFOLD = {
    "SITE_TITLE": "Carify Admin",
    "SITE_HEADER": "Carify Administration",
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": lambda request: "/static/admin/img/logo-light.svg",
        "dark": lambda request: "/static/admin/img/logo-dark.svg",
    },
    "SITE_LOGO": {
        "light": lambda request: "/static/admin/img/logo-light.svg",
        "dark": lambda request: "/static/admin/img/logo-dark.svg",
    },
    "SITE_SYMBOL": "speed",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "THEME": "dark",
    "STYLES": [
        lambda request: "/static/css/admin.css",
    ],
    "SCRIPTS": [
        lambda request: "/static/js/admin.js",
    ],
    "COLORS": {
        "primary": {
            "50": "250 245 240",
            "100": "245 235 225",
            "200": "235 215 195",
            "300": "225 185 155",
            "400": "215 155 115",
            "500": "215 126 44",   # #d77e2c (Core Copper)
            "600": "195 105 35",
            "700": "165 85 25",
            "800": "135 65 20",
            "900": "110 55 15",
            "950": "65 35 10",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("PLATFORM OVERVIEW"),
                "separator": True,
                "items": [
                    {
                        "title": _("Command Center"),
                        "icon": "dashboard",
                        "link": "/admin/",
                    },
                ],
            },
            {
                "title": _("COMMERCE ENGINE"),
                "separator": True,
                "items": [
                    {
                        "title": _("Inventory / Specimens"),
                        "icon": "inventory_2",
                        "link": "/admin/carify_app/product/",
                    },
                    {
                        "title": _("Global Catalogs"),
                        "icon": "folder_special",
                        "link": "/admin/carify_app/category/",
                    },
                    {
                        "title": _("Regional Orders"),
                        "icon": "receipt_long",
                        "link": "/admin/carify_app/order/",
                    },
                ],
            },
            {
                "title": _("PRESERVATION RITUALS"),
                "separator": True,
                "items": [
                    {
                        "title": _("Elite Solutions"),
                        "icon": "auto_fix_high",
                        "link": "/admin/carify_app/service/",
                    },
                    {
                        "title": _("Ceremony Bookings"),
                        "icon": "event",
                        "link": "/admin/carify_app/booking/",
                    },
                ],
            },
            {
                "title": _("MARKETPLACE PARTNERS"),
                "separator": True,
                "items": [
                    {
                        "title": _("Seller Profiles"),
                        "icon": "storefront",
                        "link": "/admin/carify_app/sellerprofile/",
                    },
                ],
            },
            {
                "title": _("AUDIENCE & GROWTH"),
                "separator": True,
                "items": [
                    {
                        "title": _("Newsletter Registry"),
                        "icon": "mail",
                        "link": "/admin/carify_app/newslettersubscription/",
                    },
                ],
            },
            {
                "title": _("COMMUNITY & TRUST"),
                "separator": True,
                "items": [
                    {
                        "title": _("Specimen Reviews"),
                        "icon": "reviews",
                        "link": "/admin/carify_app/review/",
                    },
                    {
                        "title": _("User Inquiries"),
                        "icon": "contact_support",
                        "link": "/admin/carify_app/productquestion/",
                    },
                ],
            },
        ],
    },
}

# REST Framework configuration
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20
}

# Email Routing - Pipe to console for dev environments to prevent ConnectionRefusedError during Signup.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
